// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD93L_VHUhMNlS9g6G2TSqVlHt6D0bRFaA',
    appId: '1:1001596513134:web:9058f61bbccfadb5f7ef7f',
    messagingSenderId: '1001596513134',
    projectId: 'fiixconn',
    authDomain: 'fiixconn.firebaseapp.com',
    storageBucket: 'fiixconn.firebasestorage.app',
    measurementId: 'G-2LPS4CZD9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaHGBaoPklkGrcd3_Kiw-yWwFxuWOoadI',
    appId: '1:1001596513134:android:e2e4cada96870fa1f7ef7f',
    messagingSenderId: '1001596513134',
    projectId: 'fiixconn',
    storageBucket: 'fiixconn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbfp4u4n9Viy9Sz5E-VhyKfzcsJKbEuU',
    appId: '1:1001596513134:ios:0caf5e35af199ee7f7ef7f',
    messagingSenderId: '1001596513134',
    projectId: 'fiixconn',
    storageBucket: 'fiixconn.firebasestorage.app',
    iosBundleId: 'com.example.fiixconn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpbfp4u4n9Viy9Sz5E-VhyKfzcsJKbEuU',
    appId: '1:1001596513134:ios:0caf5e35af199ee7f7ef7f',
    messagingSenderId: '1001596513134',
    projectId: 'fiixconn',
    storageBucket: 'fiixconn.firebasestorage.app',
    iosBundleId: 'com.example.fiixconn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD93L_VHUhMNlS9g6G2TSqVlHt6D0bRFaA',
    appId: '1:1001596513134:web:8b0f2f0719639baaf7ef7f',
    messagingSenderId: '1001596513134',
    projectId: 'fiixconn',
    authDomain: 'fiixconn.firebaseapp.com',
    storageBucket: 'fiixconn.firebasestorage.app',
    measurementId: 'G-8D02YYZ2ES',
  );
}
